apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-ts
  namespace: app


spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      api: app-ts
  template:
    metadata:
      labels:
        api: app-ts
    spec:
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      containers:
        - name: app-ts
          image: gustavoneery/app-ts:e784dc7
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: app-ts
            - secretRef:
                name: app-ts-secrets
          # env:
          #   - name: APP # Nome da variável de ambiente
          #     valueFrom:
          #       configMapKeyRef:
          #         name: app-ts # Nome do nosso ConfigMap
          #         key: app-name
          #   - name: API_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         name: app-ts-secrets
          #         key: api-key
          ports:
            - containerPort: 3000
          startupProbe:
            httpGet:
              path: /healthz # Endpoint para verificar se a aplicação está pronta para receber tráfego
              port: 3000 # A mesma porta do container
            failureThreshold: 3 # O quanto de falha a gente toléra
            successThreshold: 1 # Ter pelo menos 1 sucesso para considerar a aplicação saudável
            timeoutSeconds: 1 # Tempo para considerar a aplicação como não saudável
            periodSeconds: 10 # A cada 10 segundos, as verificações acima serão feitas
            initialDelaySeconds: 10 # caso a aplicação demore pra iniciar aumenta esse tempo
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 15
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 2
            successThreshold: 1
            periodSeconds: 10
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 192Mi
          # volumeMounts:
          #   - name: app-ts-data
          #     mountPath: /usr/src/app/uploads
      # volumes:
      #   - name: app-ts-data
      #     persistentVolumeClaim:
      #       claimName: first-pvc