name: CI

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: 'Build, Push and Deployment'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn run test
